name: Build Website

on:
  push:
    branches:
      - website

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: Build sourcefiles
        run: |
          HOST_UID=$(id -u)
          HOST_GID=$(id -g)
          docker run \
            -v "$(pwd):/src" \
            -e HOST_UID=${HOST_UID} \
            -e HOST_GID=${HOST_GID} \
            -u ${HOST_UID}:${HOST_GID} \
            floryn90/hugo:ext-alpine build -e production
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v2
        with:
          deliverables: docs/site/app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          flags: "--verbosity=debug"

      - name: Test
        run: curl "${{ steps.deploy.outputs.url }}"
